# Generated by Django 3.2 on 2023-04-11 07:07

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Имя пользователя', max_length=200, unique=True, validators=[reviews.validators.username_validator], verbose_name='Пользователь'),
        ),
    ]
