# Generated by Django 3.2 on 2023-04-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_title_ratingg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='ratingg',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
